### ISSUE TITLE
🐛 [BUG] 相机-自定义机型水印闪退

### ISSUE THREAD

**Issue by Stealthbaixiaomo** [ReChronoRain/HyperCeiler#1042]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在相机里自定义机型水印后闪退

### 模块日志

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: 2410DPN6CC
[Display]: AQ3A.240812.002
[Android Version]: 15
[Android API Level]: 35
[System Locale]: zh_CN
[Process ID]: 27654
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.camera
[Version Name]: 5.4.000730.3
[Version Code]: 540007303
[Target SDK]: 34
[Min SDK]: 29
[Error Type]: JVM
[Crash Time]: 2024-12-14T09:52:06.007
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
	at com.android.camera.fragment.bottom.action.FragmentBottomAction.provideAnimateElement(Unknown Source:171)
	at com.android.camera.fragment.bottom.action.FragmentBottomAction.initView(Unknown Source:253)
	at com.android.camera.fragment.AbstractFragment.onCreateView(Unknown Source:21)
	at com.android.camera.fragment.BaseFragment.onCreateView(Unknown Source:22)
	at androidx.fragment.app.Fragment.performCreateView(Unknown Source:19)
	at androidx.fragment.app.FragmentStateManager.createView(Unknown Source:180)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(Unknown Source:113)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(Unknown Source:277)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(Unknown Source:84)
	at androidx.fragment.app.FragmentManager.execPendingActions(Unknown Source:21)
	at androidx.fragment.app.FragmentManager$5.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:249)
	at android.os.Looper.loop(Looper.java:337)
	at android.app.ActivityThread.main(ActivityThread.java:9572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:593)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

**Comment by lingqiqi5211** [comment]
你用的相机 apk 给一份
另外请补充当时的 hyperceiler 的调试信息

**Comment by Stealthbaixiaomo** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月25日(周六) 中午12:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReChronoRain/HyperCeiler] 🐛 [BUG] 相机-自定义机型水印闪退 (Issue #1042)




 
你用的相机 apk 给一份
 另外请补充当时的 hyperceiler 的调试信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.

——————————————————

此问题只能暂时搁置，因系统版本(15 | Android 安全更新：2024-12-01)原因lsposed（https://github.com/JingMatrix/LSPosed）无法完全适配，导致目前hook相机并不会出现任何修改，亦无关于闪退的信息。等待后续lsposed版本若仍有此问题再行反馈



 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							相机_5.4.000900.9[1].apk 							 (165.0MB, 2025年2月25日 2:2) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=c69d1362022b9c00f4ee4b6233353865090d2a6831353865114d08041e075e560d505d5b52180d060850485602530a485b5404511c0559030b53525b55050b000b786585aa8ddef9833d504c051b0855095b55521f0c6354644c04125a21408475c960aa03693747b4b18c82d79f8a1980f86462313538653962&key=c69d1362022b9c00f4ee4b6233353865090d2a6831353865114d08041e075e560d505d5b52180d060850485602530a485b5404511c0559030b53525b55050b000b786585aa8ddef9833d504c051b0855095b55521f0c6354644c04125a21408475c960aa03693747b4b18c82d79f8a1980f86462313538653962&code=9beb158e&from=

**Comment by Stealthbaixiaomo** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年1月25日(周六) 中午12:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ReChronoRain/HyperCeiler] 🐛 [BUG] 相机-自定义机型水印闪退 (Issue #1042)




 
你用的相机 apk 给一份
 另外请补充当时的 hyperceiler 的调试信息
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.




相机apkMessage ID: ***@***.***&gt;
 
 	
 	 		 			从QQ邮箱发来的超大附件 	
 	 		 				 					 						 							 						 					
 					 						 							相机_5.4.000900.9[1].apk 							 (165.0MB, 2025年2月25日 2:2) 						 						 							进入下载页面 							：https://wx.mail.qq.com/ftn/download?func=3&k=c69d1362022b9c00f4ee4b6233353865090d2a6831353865114d08041e075e560d505d5b52180d060850485602530a485b5404511c0559030b53525b55050b000b786585aa8ddef9833d504c051b0855095b55521f0c6354644c04125a21408475c960aa03693747b4b18c82d79f8a1980f86462313538653962&key=c69d1362022b9c00f4ee4b6233353865090d2a6831353865114d08041e075e560d505d5b52180d060850485602530a485b5404511c0559030b53525b55050b000b786585aa8ddef9833d504c051b0855095b55521f0c6354644c04125a21408475c960aa03693747b4b18c82d79f8a1980f86462313538653962&code=9beb158e&from=

**Comment by lingqiqi5211** [comment]
https://github.com/Xposed-Modules-Repo/com.sevtinge.hyperceiler/releases/tag/3901-2.5.157_20250129
试试这个版本还有这个问题吗
