### ISSUE TITLE
🐛 [BUG] <查看电量使用详情闪退>

### ISSUE THREAD

**Issue by z1298808165** [ReChronoRain/HyperCeiler#119]
### 问题描述

小米 13u，hyperos
设置—省电与电池—耗电排行切换为电量使用详情，闪退至设置首页

### 模块日志

[ 2023-12-02T18:19:45.716     1000:  7215:  7346 I/LSPosed-Bridge  ] [D/RPackHook] startActivity 34 CallingUid:1000  CallingPid:24923  UID:1000  PID:7215 userId:0
[ 2023-12-02T18:19:45.716     1000:  7215:  7346 I/LSPosed-Bridge  ] [D/RPackHook] Intent: startActivity { calling=com.android.settings:1000:24923, rc=1000:7215, requestCode=-1, startFlags=0,intent=Intent { act=miui.intent.action.POWER_MANAGER } }
[ 2023-12-02T18:19:48.097     1000:  7215:  7346 I/LSPosed-Bridge  ] [D/RPackHook] startActivity 34 CallingUid:1000  CallingPid:12152  UID:1000  PID:7215 userId:0
[ 2023-12-02T18:19:48.098     1000:  7215:  7346 I/LSPosed-Bridge  ] [D/RPackHook] Intent: startActivity { calling=com.miui.securitycenter:1000-12152, rc=1000-7215, requestCode=-1, startFlags=0,intent=Intent { cmp=com.miui.securitycenter/com.miui.powercenter.PowerSettings (has extras) }, extras={ trackid:(java.lang.String)3b5a49e2-5af2-4c1f-b09f-b38dad7adb741701512298523, extra_settings_title_res:(java.lang.Integer)2131890125 } }
[ 2023-12-02T18:19:52.383     1000: 12152: 12152 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.Collection.toArray()' on a null object reference
	at java.util.ArrayList.addAll(ArrayList.java:677)
	at com.miui.powercenter.batteryhistory.z.t(Unknown Source:7)
	at com.miui.powercenter.batteryhistory.p.a(Unknown Source:18)
	at com.miui.powercenter.batteryhistory.x$d.a(Unknown Source:41)
	at gd.c$c$d.onClick(Unknown Source:29)
	at android.view.View.performClick(View.java:7798)
	at android.view.View.performClickInternal(View.java:7775)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:31125)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

### 复现步骤

```bash
1. 前往 '设置'
2. 点击 '省电与电池'
3. 耗电排行切换为电量使用详情
....
出现问题闪退至设置首页
```

### 问题截图

![图片注释](图片链接)

### 机型

xiaomi13ultra

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.132_20231129_6f38cf6c

**Comment by HChenX** [comment]
先别用
