### ISSUE TITLE
🐛 [BUG] 锁屏底部显示电流功能和USB设备连接请求导致systemui崩溃

### ISSUE THREAD

**Issue by dreamflandre** [ReChronoRain/HyperCeiler#136]
### 问题描述

开启锁屏底部显示电流功能，插入USB设备 软件请求USB设备访问请求弹框会导致systemui重启

### 模块日志

Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: 23127PN0CC
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 5525
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20230316.0
[Version Code]: 202303160
[Target SDK]: 34
[Min SDK]: 34
[Error Type]: JVM
[Crash Time]: 2023-12-07T09:28:48.594
[Stack Trace]:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.KeyguardIndicationController
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at k5.d.Z(Unknown Source:12)
	at androidx.activity.l.run(Unknown Source:761)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.KeyguardIndicationController
	... 12 more
[LSPosed_2023-12-07T09_30_09.975265.zip](https://github.com/ReChronoRain/HyperCeiler/files/13593515/LSPosed_2023-12-07T09_30_09.975265.zip)

### 复现步骤

```bash
1、开启系统界面-锁屏-锁屏底部显示充电信息功能
2、插入redmi buds5 pro电竞版USB闪连器
3、小米软件弹出USB设备权限请求窗口同时systemui崩溃重启
```

### 问题截图

![图片注释](图片链接)
![Screenshot_2023-12-07-09-00-34-579_com android systemui](https://github.com/ReChronoRain/HyperCeiler/assets/57754424/eedcd7d3-a7bf-4316-8bd1-d84fd396081e)

### 机型

houji

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

2.3.133_20231206

**Comment by mu7220** [comment]
已优化，使用最新canary试试

**Comment by dreamflandre** [comment]
Generated by AppErrorsTracking 1.3(6)
Project URL: https://github.com/KitsunePie/AppErrorsTracking
===============
[Device Brand]: Xiaomi
[Device Model]: 23127PN0CC
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_CN
[Process ID]: 19715
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20230316.0
[Version Code]: 202303160
[Target SDK]: 34
[Min SDK]: 34
[Error Type]: JVM
[Crash Time]: 2023-12-11T02:03:37.252
[Stack Trace]:
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.miui.charge.ChargeUtils
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:536)
	at l5.h.d0(Unknown Source:12)
	at d4.b.run(Unknown Source:51)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8669)
	... 3 more
Caused by: java.lang.ClassNotFoundException: com.miui.charge.ChargeUtils
	... 12 more
[LSPosed_2023-12-11T02_05_50.881459.zip](https://github.com/ReChronoRain/HyperCeiler/files/13628777/LSPosed_2023-12-11T02_05_50.881459.zip)

似乎小米耳机的USB设备权限请求还是会导致systemui重启

**Comment by mu7220** [comment]
目前 canary 的最新版本(2.3.135_20231229_3e1c4d8f)可以试一下还会不会出现这个问题

**Comment by dreamflandre** [comment]
好了
