### ISSUE TITLE
🐛 [BUG] 系统框架|其他|清理分享菜单选择已选应用闪退

### ISSUE THREAD

**Issue by Zpcola** [ReChronoRain/HyperCeiler#138]
### 问题描述

点击已选应用，转圈圈后闪退回系统框架|其他

### 模块日志

[ 2023-12-08T09:42:19.289    10144: 20060: 20060 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Set
	at android.app.SharedPreferencesImpl.getStringSet(SharedPreferencesImpl.java:312)
	at w1.c.onBindViewHolder(Unknown Source:19)
	at androidx.recyclerview.widget.q0.onBindViewHolder(SourceFile:1)
	at androidx.recyclerview.widget.q0.bindViewHolder(Unknown Source:152)
	at androidx.recyclerview.widget.i1.k(Unknown Source:1203)
	at androidx.recyclerview.widget.g0.b(Unknown Source:62)
	at androidx.recyclerview.widget.LinearLayoutManager.O0(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.D0(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.Y(Unknown Source:841)
	at androidx.recyclerview.widget.RecyclerView.r(Unknown Source:60)
	at androidx.recyclerview.widget.RecyclerView.p(Unknown Source:71)
	at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at moralnorm.springback.view.SpringBackLayout.onLayout(Unknown Source:32)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1103)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at moralnorm.appcompat.internal.app.widget.ActionBarOverlayLayout.onLayout(Unknown Source:0)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:874)
	at android.view.View.layout(View.java:23881)
	at android.view.ViewGroup.layout(ViewGroup.java:6454)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4207)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3577)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2543)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9424)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1451)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1459)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1089)
	at android.view.Choreographer.doFrame(Choreographer.java:1003)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1431)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99](
[LSPosed_2023-12-08T10_06_19.721658.zip](https://github.com/ReChronoRain/HyperCeiler/files/13608140/LSPosed_2023-12-08T10_06_19.721658.zip)

### 复现步骤

```bash
1. 前往 '系统框架|其他|清理分享菜单'
2. 点击 '已选应用'

闪退
```

### 问题截图

![IMG_20231208_093812](https://github.com/ReChronoRain/HyperCeiler/assets/116626041/5d8558c2-a797-4f48-9064-a1a7422efc9c)

![IMG_20231208_093824](https://github.com/ReChronoRain/HyperCeiler/assets/116626041/d3ad0b22-272d-4e60-b6c5-328074f6184e)

### 机型

K60

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

2.3.133_20231208

**Comment by wayner6** [comment]
@Zpcola 可以看下你都勾选了清理哪些应用的分享菜单吗？我勾选了一些应用如淘宝之类的软件会导致软件无法使用
