### ISSUE TITLE
🐛 [BUG] <控制中心导致系统界面奔溃重启>

### ISSUE THREAD

**Issue by Jiangyufeng7** [ReChronoRain/HyperCeiler#139]
### 问题描述

下拉至控制中心(非通知中心)，等待一会或直接启用控制中心磁贴功能会导致"系统界面"100%奔溃重启

### 模块日志

================================================================
    Generated by AppErrorsTracking 1.3(6)
    Project URL: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: Xiaomi
[Device Model]: 23078RKD5C
[Display]: TP1A.220624.014
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 12300
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20220714.0
[Version Code]: 202207140
[Target SDK]: 33
[Min SDK]: 33
[Error Type]: JVM
[Crash Time]: 2023-12-08T10:56:57.996
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
	at LSPHooker_.getOverExpansion(Unknown Source:14)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateStackPosition(NotificationStackScrollLayout.java:1355)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateStackPosition(NotificationStackScrollLayout.java:1333)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateContentHeight(NotificationStackScrollLayout.java:2400)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.onLayout(NotificationStackScrollLayout.java:1146)
	at android.view.View.layout(View.java:24043)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1695)
	at android.view.View.layout(View.java:24043)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24043)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24043)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4271)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3645)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2574)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9649)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

================================================================
    Generated by AppErrorsTracking 1.3(6)
    Project URL: https://github.com/KitsunePie/AppErrorsTracking
================================================================
[Device Brand]: Xiaomi
[Device Model]: 23078RKD5C
[Display]: TP1A.220624.014
[Android Version]: 13
[Android API Level]: 33
[System Locale]: zh_CN
[Process ID]: 23534
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.android.systemui
[Version Name]: 20220714.0
[Version Code]: 202207140
[Target SDK]: 33
[Min SDK]: 33
[Error Type]: JVM
[Crash Time]: 2023-12-08T10:57:18.675
[Stack Trace]:
java.lang.NullPointerException: Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
	at LSPHooker_.getOverExpansion(Unknown Source:14)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateStackPosition(NotificationStackScrollLayout.java:1355)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateStackPosition(NotificationStackScrollLayout.java:1333)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.setExpandedHeight(NotificationStackScrollLayout.java:1448)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayout.updateTopPadding(NotificationStackScrollLayout.java:2708)
	at com.android.systemui.statusbar.notification.stack.NotificationStackScrollLayoutController.updateTopPadding(NotificationStackScrollLayoutController.java:1201)
	at com.android.systemui.statusbar.phone.NotificationPanelViewController.requestScrollerTopPaddingUpdate(NotificationPanelViewController.java:2826)
	at com.android.systemui.statusbar.phone.NotificationPanelViewController.positionClockAndNotifications(NotificationPanelViewController.java:1444)
	at com.android.systemui.statusbar.phone.NotificationPanelViewController.positionClockAndNotifications(NotificationPanelViewController.java:1410)
	at com.android.systemui.statusbar.phone.NotificationPanelViewController.-$$Nest$mpositionClockAndNotifications(Unknown Source:0)
	at com.android.systemui.statusbar.phone.NotificationPanelViewController$OnLayoutChangeListener.onLayoutChange(NotificationPanelViewController.java:5102)
	at android.view.View.layout(View.java:24062)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24043)
	at android.view.ViewGroup.layout(ViewGroup.java:6522)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:4271)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3645)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2574)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9649)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1386)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1394)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1013)
	at android.view.Choreographer.doFrame(Choreographer.java:911)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1366)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:210)
	at android.os.Looper.loop(Looper.java:299)
	at android.app.ActivityThread.main(ActivityThread.java:8136)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)

### 复现步骤

```bash
1. 下拉'控制中心'
2. 点击 '控制中心磁贴'

....
出现问题'系统界面奔溃'
```

### 问题截图

![图片注释](图片链接)
无

### 机型

Redmi k50pro

### MIUI/HyperOS 版本

MIUI14

### Android 版本

Android 13

### HyperCeiler 版本

2.3.132_20231204

**Comment by HChenX** [comment]
无法复现
