### ISSUE TITLE
🐛 [BUG] 系统界面-通知与控制中心-通知设置

### ISSUE THREAD

**Issue by zxjzxj0010** [ReChronoRain/HyperCeiler#153]
### 问题描述

系统界面-通知与控制中心-通知设置会导致系统界面组建崩溃，且通知透明度不生效，模糊图层和“原生通知”模式不适配。

### 模块日志

----part 17 start----
[ 2023-12-11T16:09:36.734        0:  1418:  1485 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2023-12-11T16:09:36.734475.log
[ 2023-12-11T16:09:36.735     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.NotificationBackgroundView.setCustomBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:19)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:16)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.735     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:16)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.735     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.NotificationBackgroundView.setCustomBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:19)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBlurBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBackgroundBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:187)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:4)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.735     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBlurBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBackgroundBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:187)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:4)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.736     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.NotificationBackgroundView.setCustomBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:19)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:16)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.736     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:16)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.736     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:11)
	at com.android.systemui.statusbar.notification.row.NotificationBackgroundView.setCustomBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:19)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBlurBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBackgroundBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:187)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:4)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.736     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.f(Unknown Source:0)
	at bULnEORY.I.oe.rw.KJwWd.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.callMethod(SourceFile:2)
	at j3.d.afterHookedMethod(Unknown Source:33)
	at bULnEORY.I.oe.rw.KJwWd.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.setCustomBackground(Unknown Source:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBlurBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:15)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.updateBackgroundBg(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:187)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.initBackground(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:4)
	at com.android.systemui.statusbar.notification.row.ActivatableNotificationView.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:37)
	at com.android.systemui.statusbar.notification.row.ExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at com.android.systemui.statusbar.notification.row.MiuiExpandableNotificationRow.onFinishInflate(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:1)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1166)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1109)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:707)
	at java.lang.reflect.Method.invoke(Native Method)
	at XEOsj.GQd.vHK.ejtF.qXoDPPjrSx.HookBridge.invokeOriginalMethod(Native Method)
	at J.callback(Unknown Source:193)
	at LSPHooker_.inflate(Unknown Source:21)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at androidx.asynclayoutinflater.view.AsyncLayoutInflater$InflateThread.run(go/retraceme 16a753734fc2b258c38c04cc8e92035420d3c19737a5f37ed0bdc519e3ecf57e:18)
[ 2023-12-11T16:09:36.759     1000: 12806: 13218 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: com.android.systemui.statusbar.notification.row.NotificationBackgroundView#headsUp()
	at bULnEORY.I.oe.rw.KJwWd.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### 机型

xiaomi14

### MIUI/HyperOS 版本

Xiaomi HyperOS 1.0

### Android 版本

Android 14

### HyperCeiler 版本

20231211

**Comment by zxjzxj0010** [comment]
（主要是第三方主题的通知模糊不生效，而且希望默认的通知效果的透明度）

**Comment by zxjzxj0010** [comment]
（主要是第三方主题的通知模糊不生效，而且默认的通知效果

**Comment by Ankit2502** [comment]
> (Mainly because the notification blur of the third-party theme does not take effect, and I want to change the transparency of the default notification effect)

I have similar issue but it is working for me (too much working)

![Screenshot_2024-01-27-20-41-43-551_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/89592455/bae9d797-e22d-45e1-8ee7-d0644ebfb45b)

When ever I enable remove notification blur restrictions the blur is gone and everything become complete transparent...

**Comment by mu7220** [comment]
HyperOS 不打算再进行修复（在 MIUI 阶段这个功能就呈现出较难维护）
