### ISSUE TITLE
🐛 [BUG] EEA/TW HyperOS系統中 hook系統桌面會造成桌面無限FC

### ISSUE THREAD

**Issue by Hs0** [ReChronoRain/HyperCeiler#294]
### 问题描述

機型: 小米13
ROM版本: V816.0.1.0.UMCEUXM (EEA版) & V816.0.1.0.UMCTWXM (TW版)
問題: 在EEA/TW HyperOS系統中，hook系統桌面會造成桌面無限FC，無論是哪個桌面版本都會出現這個問題

### 模块日志

[Device Brand]: Xiaomi
[Device Model]: 2211133G
[Display]: UKQ1.230804.001 release-keys
[Android Version]: 14
[Android API Level]: 34
[System Locale]: zh_TW
[Process ID]: 29234
[User ID]: 0
[CPU ABI]: arm64-v8a
[Package Name]: com.miui.home
[Version Name]: RELEASE-4.39.14.7750-12111906
[Version Code]: 439147750
[Target SDK]: 33
[Min SDK]: 30
[Error Type]: JVM
[Crash Time]: 2024-01-20T21:17:57.546
[Stack Trace]:
java.lang.RuntimeException: Unable to instantiate application com.miui.home.launcher.Application package com.miui.home: java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap miui.content.res.ThemeValues.mIntegers' on a null object reference in method 'void miui.content.res.ThemeValues.putAll(miui.content.res.ThemeValues)'
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1495)
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1424)
 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7448)
 at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2382)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.app.ActivityThread.main(ActivityThread.java:8759)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.HashMap miui.content.res.ThemeValues.mIntegers' on a null object reference in method 'void miui.content.res.ThemeValues.putAll(miui.content.res.ThemeValues)'
 at miui.content.res.ThemeValues.putAll(ThemeValues.java:47)
 at android.util.Log.printlns(Log.java:489)
 at android.util.Log.e(Log.java:280)
 at com.miui.home.launcher.DeviceConfig.loadThemeResource(DeviceConfig.java:933)
 at com.miui.home.launcher.DeviceConfig.Init(DeviceConfig.java:390)
 at com.miui.home.launcher.Application.attachBaseContext(Application.java:108)
 at android.app.Application.attach(Application.java:368)
 at android.app.Instrumentation.newApplication(Instrumentation.java:1287)
 at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1487)
 ... 11 more

### 复现步骤

```bash
1. 目前發現是在小米13 EEA及TW版的HyperOS中出現這個狀況，已知使用官方桌面與各版本MOD桌面都有這問題
2. 在LSP中hook系統桌面，不對桌面的任何功能進行修改就直接重啟系統桌面
3. 然後就會進入FC迴圈了
4. 進REC清除package cache + Dalvik cache + cache 後的第一次開機可以恢復正常，但再次重啟手機或重啟桌面後會複現這個問題
5. 在HyperCeiler的安全模式中勾選系統桌面，一樣會FC，必須直接進LSP取消hook系統桌面才能正常進入桌面，並且桌面圖標位置會被重設為默認排序
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

![image](https://github.com/ReChronoRain/HyperCeiler/assets/14960173/77a23ce0-13e7-458e-93f8-78e5375d3781)

**Comment by HChenX** [comment]
未知
