### ISSUE TITLE
🐛 [BUG] HyperOS 固定应用出现较大问题

### ISSUE THREAD

**Issue by LLKawi** [ReChronoRain/HyperCeiler#323]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

升了hyperos后发现固定应用又出问题了

1. 状态栏判定很奇怪，经常是按了啥反应没有，全靠运气
2. 固定应用时系统界面重启
3. 侧边栏无法固定

### 模块日志

系统界面崩溃日志
```
[ 2024-01-29T21:48:08.692     1000: 15706: 15706 I/LSPosed-Bridge  ] Crash unexpectedly: java.lang.NoSuchMethodError: com.android.systemui.statusbar.phone.AutoHideController#scheduleAutoHide()
	at V.DqMT.uArfjUEeKpzskXN.XposedHelpers.lambda$findMethodBestMatch$5(Unknown Source:6)
	at V.DqMT.uArfjUEeKpzskXN.XposedHelpers.f(Unknown Source:0)
	at V.DqMT.uArfjUEeKpzskXN.c.get(Unknown Source:8)
	at java.util.Optional.orElseThrow(Optional.java:404)
	at V.DqMT.uArfjUEeKpzskXN.XposedHelpers.findMethodBestMatch(SourceFile:1)
	at V.DqMT.uArfjUEeKpzskXN.XposedHelpers.findMethodBestMatch(SourceFile:3)
	at V.DqMT.uArfjUEeKpzskXN.XposedHelpers.callMethod(SourceFile:2)
	at y1.d.onChange(SourceFile:2)
	at android.database.ContentObserver.onChange(ContentObserver.java:154)
	at y1.d.onChange(Unknown Source:9)
	at android.database.ContentObserver.onChange(ContentObserver.java:170)
	at android.database.ContentObserver.onChange(ContentObserver.java:188)
	at android.database.ContentObserver.onChange(ContentObserver.java:210)
	at android.database.ContentObserver.onChange(ContentObserver.java:222)
	at android.database.ContentObserver.lambda$dispatchChange$0(ContentObserver.java:304)
	at android.database.ContentObserver.$r8$lambda$ZTAX5Dz0QB2gJk_nBFGhENlKHoI(Unknown Source:0)
	at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
[ 2024-01-29T21:48:09.157     1000:  2757:  2822 I/LSPosed-Bridge  ] [AppErrorsTracking][I][android] Received crash application data --pid 15706
[ 2024-01-29T21:48:09.191     1000:  2757:  2822 I/LSPosed-Bridge  ] [AppErrorsTracking][E][android] Application "com.android.systemui" has stopped --pid 15706
```

### 复现步骤

```bash
1. 长按状态栏，尝试固定
2. ...
```

### HyperCeiler 设备信息

![image](https://github.com/ReChronoRain/HyperCeiler/assets/62250232/e516570d-c24e-4038-b63c-68f45c4253ee)

**Comment by HChenX** [comment]
等我整理

**Comment by hexadecimal233** [comment]
更新，hyperos还会在固定时闪退
