### ISSUE TITLE
「bug」在时钟指示器内启用修改后桌面会一直重新加载并且提示应用闪退

### ISSUE THREAD

**Issue by sxyofficial** [ReChronoRain/HyperCeiler#471]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

在hyperceiler→系统界面→状态栏→时钟指示器启用修改后，系统桌面会一直重加载，三方应用异常分析一直报hyperceiler闪退

### 模块日志

![1710904456226](https://github.com/ReChronoRain/HyperCeiler/assets/138845393/66e45d40-d90f-4f84-8f16-7e95d52c721e)
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.sevtinge.hyperceiler/com.sevtinge.hyperceiler.ui.SubSettings}: java.lang.NullPointerException: Attempt to invoke virtual method 'void moralnorm.appcompat.app.ActionBar.setEndView(android.view.View)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3991)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4144)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2589)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void moralnorm.appcompat.app.ActionBar.setEndView(android.view.View)' on a null object reference
	at P1.c.setActionBarEndView(Unknown Source:4)
	at com.sevtinge.hyperceiler.ui.fragment.base.SettingsPreferenceFragment.onCreatePreferences(Unknown Source:137)
	at moralnorm.preference.PreferenceFragmentCompat.onCreate(Unknown Source:72)
	at moralnorm.preference.compat.PreferenceFragment.onCreate(Unknown Source:0)
	at com.sevtinge.hyperceiler.ui.fragment.base.SettingsPreferenceFragment.onCreate(Unknown Source:0)
	at androidx.fragment.app.J.performCreate(Unknown Source:21)
	at androidx.fragment.app.n0.i(Unknown Source:210)
	at androidx.fragment.app.g0.M(Unknown Source:57)
	at androidx.fragment.app.g0.u(Unknown Source:33)
	at androidx.fragment.app.M.onCreate(Unknown Source:26)
	at moralnorm.appcompat.app.AppCompatActivity.access$001(Unknown Source:0)
	at moralnorm.appcompat.app.AppCompatActivity$Callback.onCreate(Unknown Source:2)
	at moralnorm.appcompat.app.AppDelegate.onCreate(Unknown Source:20)
	at moralnorm.appcompat.app.AppCompatActivity.onCreate(Unknown Source:2)
	at P1.c.onCreate(Unknown Source:7)
	at P1.e.onCreate(Unknown Source:0)
	at P1.k.onCreate(Unknown Source:0)
	at android.app.Activity.performCreate(Activity.java:8891)
	at android.app.Activity.performCreate(Activity.java:8856)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1471)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3973)
	... 12 more
[LSPosed_2024-03-20T11_20_22.336202.zip](https://github.com/ReChronoRain/HyperCeiler/files/14661649/LSPosed_2024-03-20T11_20_22.336202.zip)

### 复现步骤

```bash
在hyperceiler→系统界面→状态栏→时钟指示器启用修改后，系统桌面会一直重加载，三方应用异常分析一直报hyperceiler闪退
```

### 问题截图

![图片注释](图片链接)
![1710904637978](https://github.com/ReChronoRain/HyperCeiler/assets/138845393/5aefb8b8-5596-43a2-83c3-a547704d1aa2)

### HyperCeiler 设备信息

![图片注释](图片链接)
![Image_1710904665693](https://github.com/ReChronoRain/HyperCeiler/assets/138845393/e228ba60-6ba7-4534-9432-0656b9d72535)

**Comment by mu7220** [comment]
从提供的日志来看，目前只有应用闪退的情况
尝试下 github action 最新的提交看看还会不会有这个问题
