### ISSUE TITLE
🐛 [BUG] 无法使用 电量和性能\禁止恢复电池优化白名单

### ISSUE THREAD

**Issue by qdsp6sw** [ReChronoRain/HyperCeiler#680]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [x] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

电量和性能\禁止恢复电池优化白名单无效，开启此功能后，重启电量和性能会自动恢复白名单APP的“无限制”
不确定是不是DexKit的问题
电量和性能反编译
![image](https://github.com/ReChronoRain/HyperCeiler/assets/163347875/ddc12ff9-97e1-4647-b4b6-1720a8ed18f9)
报错
![image](https://github.com/ReChronoRain/HyperCeiler/assets/163347875/5cc73db6-b9ea-4884-8239-da7bf3320fcb)
手动出个StackTrace
![image](https://github.com/ReChronoRain/HyperCeiler/assets/163347875/24c84d39-172d-44e2-8767-edcbb111027c)

### 模块日志

```
[ 2024-06-10T18:26:06.446     1000:  9129:  9129 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~eQMS3S6Gm-O_eRX2MS5T7A==/com.sevtinge.hyperceiler-AajdfVVIZaDvqLOKiCfX4A==/base.apk
[ 2024-06-10T18:26:06.570     1000:  9129:  9129 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-06-10T18:26:07.280     1000:  9129:  9129 I/LSPosed-Bridge  ] [HyperCeiler][I][com.miui.powerkeeper]: versionName = 4.2.00, versionCode = 40200
[ 2024-06-10T18:26:07.292     1000:  9129:  9129 I/LSPosed-Bridge  ] [HyperCeiler][HyperCeiler][I]: init lpparam: [HYzozExQOPW.cee.GZ.CcW.callbacks.XC_LoadPackage$LoadPackageParam@a06c39b], classLoader: [dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/PowerKeeper/PowerKeeper.apk"],nativeLibraryDirectories=[/system/app/PowerKeeper/lib/arm64, /system/app/PowerKeeper/PowerKeeper.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]]], pkg name: com.miui.powerkeeper
[ 2024-06-10T18:26:07.758     1000:  9129:  9129 E/LSPosed-Bridge  ] java.lang.RuntimeException: failed:
java.lang.ClassNotFoundException: Didn't find class "Ljava.lang.String;" on path: DexPathList[[zip file "/system/app/PowerKeeper/PowerKeeper.apk"],nativeLibraryDirectories=[/system/app/PowerKeeper/lib/arm64, /system/app/PowerKeeper/PowerKeeper.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.throwRuntime(DexKit.java:529)
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.getClass(DexKit.java:523)
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.stringToClassArray(DexKit.java:538)
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.getFileCache(DexKit.java:466)
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.run(DexKit.java:314)
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.getDexKitBridge(DexKit.java:303)
	at com.sevtinge.hyperceiler.module.base.dexkit.DexKit.getDexKitBridge(DexKit.java:255)
	at com.sevtinge.hyperceiler.module.hook.powerkeeper.PreventBatteryWitelist.init(PreventBatteryWitelist.java:52)
	at com.sevtinge.hyperceiler.module.base.BaseHook.onCreate(BaseHook.java:44)
	at com.sevtinge.hyperceiler.module.base.BaseModule.initHook(BaseModule.java:102)
	at com.sevtinge.hyperceiler.module.app.PowerKeeper.handleLoadPackage(PowerKeeper.java:38)
	at com.sevtinge.hyperceiler.module.base.BaseModule.init(BaseModule.java:79)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.sevtinge.hyperceiler.module.base.BaseXposedInit.invoke(BaseXposedInit.java:217)
	at com.sevtinge.hyperceiler.module.base.BaseXposedInit.invokeHookInit(BaseXposedInit.java:200)
	at com.sevtinge.hyperceiler.module.base.BaseXposedInit.init(BaseXposedInit.java:133)
	at com.sevtinge.hyperceiler.XposedInit.handleLoadPackage(XposedInit.java:100)
	at HYzozExQOPW.cee.GZ.CcW.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at HYzozExQOPW.cee.GZ.CcW.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at HYzozExQOPW.cee.GZ.CcW.callbacks.XCallback.callAll(Unknown Source:26)
	at g0.a(Unknown Source:285)
	at java.lang.reflect.Method.invoke(Native Method)
	at J.callback(Unknown Source:253)
	at LSPHooker_.createOrUpdateClassLoaderLocked(Unknown Source:11)
	at android.app.LoadedApk.getClassLoader(LoadedApk.java:1139)
	at android.app.LoadedApk.getResources(LoadedApk.java:1398)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3100)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:3092)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7199)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
[ 2024-06-10T18:26:07.758     1000:  9129:  9129 I/LSPosed-Bridge  ] [HyperCeiler][E][com.miui.powerkeeper][PreventBatteryWitelist]: Hook Failed , by: java.lang.RuntimeException: failed: java.lang.ClassNotFoundException: Didn't find class "Ljava.lang.String;" on path: DexPathList[[zip file "/system/app/PowerKeeper/PowerKeeper.apk"],nativeLibraryDirectories=[/system/app/PowerKeeper/lib/arm64, /system/app/PowerKeeper/PowerKeeper.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]

```

### 复现步骤

```bash
1. 前往 '...'
2. 点击 '....'

....
出现问题
```

### 问题截图

![图片注释](图片链接)

### HyperCeiler 设备信息

Debug Info by HyperCeiler

VersionName = 2.4.146_22a383d4_r3135
VersionCode = 146
BuildTime = (UTC+0:00) 2024-06-10 18:24:16
BuildType = debug
GitHash = 22a383d4e49c3371aaba9e8c543af0790f49bb35
GitCode = 3135
Debug = true
ApplicationId = com.sevtinge.hyperceiler

MarketName = Mi 10S
DeviceName = thyme
Model = M2102J2SC
Brand = Xiaomi
Manufacture = Xiaomi
Board = thyme
Soc = SM8250
ModDevice = thyme
Characteristics = nosdcard
Pad = false
FingerPrint = Xiaomi/thyme/thyme:13/TKQ1.221114.001/V816.0.3.0.TGACNXM:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = 89f531fde0ad6810

AndroidVersion = 33
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.3.0.TGACNXM
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = pangu-build-component-system-294653-8vvcj-v23nz-0x6s4
BuildDate = Thu Apr 18 12:52:14 UTC 2024

Signature = CA:2E:D8:82:69:F9:0A:6F:2B:33:31:C5:EA:05:E6:27:80:7A:89:D6:21:DB:87:55:2A:EE:32:68:21:20:F6:27
SignCheckPass = false
ModuleActive = true
RootPermission = false

**Comment by qdsp6sw** [comment]
Done with dexkit cache optimization
