### ISSUE TITLE
🐛 [BUG] 新UI MIUIX V3 5个bug

### ISSUE THREAD

**Issue by Lxeon** [ReChronoRain/HyperCeiler#687]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

使用最新CI 2.4.146_a014a763_r3182_146_canary.apk

1. 新UI的版本号应该是3.0，但是最新CI版本号为2.4.xxx
2. 主页右上角原本应该有重启作用域的按钮，新UI没有，而且盲点会出现闪退
3. 进入第1页往后的子项目时（如 应用商店），再返回到主页时，会跳回第一页
4. 主页 tip 出现 “Tip: Tip: Tip: Tip: Tip:”
5. cpu占用高，前后台都高
### 模块日志

----part 3 start----
[ 2024-06-14T02:08:29.760    10376: 16441: 16441 I/LSPosed-Bridge  ] Crash unexpectedly: android.view.InflateException: Binary XML file line #12 in com.sevtinge.hyperceiler:layout/item_mutiplechoice: Binary XML file line #12 in com.sevtinge.hyperceiler:layout/item_mutiplechoice: Error inflating class fan.appcompat.widget.CheckedTextView
Caused by: android.view.InflateException: Binary XML file line #12 in com.sevtinge.hyperceiler:layout/item_mutiplechoice: Error inflating class fan.appcompat.widget.CheckedTextView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:879)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1031)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:986)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at u0.k.onCreateViewHolder(Unknown Source:12)
	at androidx.recyclerview.widget.e0.createViewHolder(Unknown Source:14)
	at androidx.recyclerview.widget.z0.l(Unknown Source:1015)
	at androidx.recyclerview.widget.T.b(Unknown Source:62)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:761)
	at androidx.recyclerview.widget.RecyclerView.d(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:67)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChild(ViewGroup.java:7054)
	at fan.springback.view.SpringBackLayout.onMeasure(Unknown Source:13)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at fan.appcompat.internal.widget.NestedScrollViewExpander.onMeasure(Unknown Source:117)
	at android.view.View.measure(View.java:28001)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(Unknown Source:38)
	at fan.appcompat.internal.widget.NestedScrollViewExpandContainer.measureChildWithMargins(Unknown Source:9)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at fan.appcompat.internal.widget.DialogParentPanel.onMeasure(Unknown Source:15)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
[ 2024-06-14T02:08:29.760    10376: 16441: 16441 I/LSPosed-Bridge  ] 	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:826)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4717)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3235)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3591)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2933)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10224)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1607)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x36040106 a=15}, theme={InheritanceMap=[id=0x3611009ecom.sevtinge.hyperceiler:style/ThemeOverlay.Preference.DayNight, id=0x3611009fcom.sevtinge.hyperceiler:style/ThemeOverlay.Preference.Light, id=0x3611009ccom.sevtinge.hyperceiler:style/ThemeOverlay.Preference, id=0x36110010com.sevtinge.hyperceiler:style/BasePreferenceThemeOverlay], Themes=[com.sevtinge.hyperceiler:style/ThemeOverlay.Preference.DayNight, not forced, com.sevtinge.hyperceiler:style/NavigatorActivityTheme, forced, com.sevtinge.hyperceiler:style/Theme.Settings.MiuiSettings, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1010)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:994)
	at android.view.View.<init>(View.java:5836)
	at android.widget.TextView.<init>(TextView.java:1171)
	at android.widget.CheckedTextView.<init>(CheckedTextView.java:90)
	at android.widget.CheckedTextView.<init>(CheckedTextView.java:86)
	at fan.appcompat.widget.CheckedTextView.<init>(SourceFile:3)
	at fan.appcompat.widget.CheckedTextView.<init>(SourceFile:2)
	... 80 more
[ 2024-06-14T02:08:29.767     1000:  2716:  6431 I/LSPosed-Bridge  ] [HyperCeiler][E][[HyperCeiler]: CrashHook]: context: android.app.ContextImpl@6c49ad5 pkg: android proc: ProcessRecord{8ef282 16441:com.sevtinge.hyperceiler/u0a376} crash: android.app.ApplicationErrorReport$ParcelableCrashInfo@96cd411 short: java.lang.UnsupportedOperationException long: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x36040106 a=15}, theme={InheritanceMap=[id=0x3611009ecom.sevtinge.hyperceiler:style/ThemeOverlay.Preference.DayNight, id=0x3611009fcom.sevtinge.hyperceiler:style/ThemeOverlay.Preference.Light, id=0x3611009ccom.sevtinge.hyperceiler:style/ThemeOverlay.Preference, id=0x36110010com.sevtinge.hyperceiler:style/BasePreferenceThemeOverlay], Themes=[com.sevtinge.hyperceiler:style/ThemeOverlay.Preference.DayNight, not forced, com.sevtinge.hyperceiler:style/NavigatorActivityTheme, forced, com.sevtinge.hyperceiler:style/Theme.Settings.MiuiSettings, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]} stack: android.view.InflateException: Binary XML file line #12 in com.sevtinge.hyperceiler:layout/item_mutiplechoice: Binary XML file line #12 in com.sevtinge.hyperceiler:layout/item_mutiplechoice: Error inflating class fan.appcompat.widget.CheckedTextView
Caused by: android.view.InflateException: Binary XML file line #12 in com.sevtinge.hyperceiler:layout/item_mutiplechoice: Error inflating class fan.appcompat.widget.CheckedTextView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:879)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1031)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:986)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:545)
	at u0.k.onCreateViewHolder(Unknown Source:12)
	at androidx.recyclerview.widget.e0.createViewHolder(Unknown Source:14)
	at androidx.recyclerview.widget.z0.l(Unknown Source:1015)
	at androidx.recyclerview.widget.T.b(Unknown Source:62)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(Unknown Source:0)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(Unknown Source:48)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(Unknown Source:761)
	at androidx.recyclerview.widget.RecyclerView.d(Unknown Source:66)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(Unknown Source:67)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChild(ViewGroup.java:7054)
	at fan.springback.view.SpringBackLayout.onMeasure(Unknown Source:13)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at fan.appcompat.internal.widget.NestedScrollViewExpander.onMeasure(Unknown Source:117)
	at android.view.View.measure(View.java:28001)
	at androidx.core.widget.NestedScrollView.measureChildWithMargins(Unknown Source:38)
[ 2024-06-14T02:08:29.767     1000:  2716:  6431 I/LSPosed-Bridge  ] 	at fan.appcompat.internal.widget.NestedScrollViewExpandContainer.measureChildWithMargins(Unknown Source:9)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.core.widget.NestedScrollView.onMeasure(Unknown Source:0)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at fan.appcompat.internal.widget.DialogParentPanel.onMeasure(Unknown Source:15)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7083)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:826)
	at android.view.View.measure(View.java:28001)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4717)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3235)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3591)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2933)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10224)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1634)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1643)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1172)
	at android.view.Choreographer.doFrame(Choreographer.java:1076)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1607)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8767)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 13: TypedValue{t=0x2/d=0x36040106 a=15}, theme={InheritanceMap=[id=0x3611009ecom.sevtinge.hyperceiler:style/ThemeOverlay.Preference.DayNight, id=0x3611009fcom.sevtinge.hyperceiler:style/ThemeOverlay.Preference.Light, id=0x3611009ccom.sevtinge.hyperceiler:style/ThemeOverlay.Preference, id=0x36110010com.sevtinge.hyperceiler:style/BasePreferenceThemeOverlay], Themes=[com.sevtinge.hyperceiler:style/ThemeOverlay.Preference.DayNight, not forced, com.sevtinge.hyperceiler:style/NavigatorActivityTheme, forced, com.sevtinge.hyperceiler:style/Theme.Settings.MiuiSettings, forced, android:style/Theme.DeviceDefault.Light.DarkActionBar, forced]}
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:1010)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:994)
	at android.view.View.<init>(View.java:5836)
	at android.widget.TextView.<init>(TextView.java:1171)
	at android.widget.CheckedTextView.<init>(CheckedTextView.java:90)
	at android.widget.CheckedTextView.<init>(CheckedTextView.java:86)
[ 2024-06-14T02:08:29.767     1000:  2716:  6431 I/LSPosed-Bridge  ] 	at fan.appcompat.widget.CheckedTextView.<init>(SourceFile:3)
	at fan.appcompat.widget.CheckedTextView.<init>(SourceFile:2)
	... 80 more
 time: 1718302109767 pid: 16441 uid: 10376
[ 2024-06-14T02:08:46.329    10075: 28382: 28382 I/LSPosed-Bridge  ] Loading legacy module com.sevtinge.hyperceiler from /data/app/~~8rQTXlm2KnxwataKlWwqIA==/com.sevtinge.hyperceiler-CwS3KHhie0KcTsD_MPB55Q==/base.apk
[ 2024-06-14T02:08:46.340    10075: 28382: 28382 I/LSPosed-Bridge  ]   Loading class com.sevtinge.hyperceiler.XposedInit
[ 2024-06-14T02:08:46.413    10075: 28382: 28382 I/LSPosed-Bridge  ] [HyperCeiler][I][com.android.externalstorage]: versionName = 14, versionCode = 34
[ 2024-06-14T02:08:46.414    10075: 28382: 28382 I/LSPosed-Bridge  ] [HyperCeiler][HyperCeiler][I]: init lpparam: [VV.joQSOk.Fu.W.dij.iYa.callbacks.XC_LoadPackage$LoadPackageParam@349fbee], classLoader: [dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/ExternalStorageProvider/ExternalStorageProvider.apk"],nativeLibraryDirectories=[/system/priv-app/ExternalStorageProvider/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]]], pkg name: com.android.externalstorage
[ 2024-06-14T02:08:46.417    10075: 28382: 28382 I/LSPosed-Bridge  ] [HyperCeiler][HyperCeiler][I]: init lpparam: [VV.joQSOk.Fu.W.dij.iYa.callbacks.XC_LoadPackage$LoadPackageParam@349fbee], classLoader: [dalvik.system.PathClassLoader[DexPathList[[zip file "/system/priv-app/ExternalStorageProvider/ExternalStorageProvider.apk"],nativeLibraryDirectories=[/system/priv-app/ExternalStorageProvider/lib/arm64, /system/lib64, /system_ext/lib64, /system/lib64, /system_ext/lib64]]]], pkg name: com.android.externalstorage

### 问题截图

1.
![Screenshot_2024-06-14-02-17-09-885_org telegram plus](https://github.com/ReChronoRain/HyperCeiler/assets/28784869/25428665-7ea1-41b2-ba06-d97c9ab76c39)

2.
https://github.com/ReChronoRain/HyperCeiler/assets/28784869/d85f1ef2-f5cf-4272-93d3-6a61dc8112c7

3.
https://github.com/ReChronoRain/HyperCeiler/assets/28784869/e648cfad-ce9f-46fb-926a-f8286567714b

4.
![Screenshot_2024-06-14-01-52-15-653_com sevtinge hyperceiler](https://github.com/ReChronoRain/HyperCeiler/assets/28784869/5fbf28e1-3d39-4c2d-97ca-8a51c3f2f694)

5.

https://github.com/ReChronoRain/HyperCeiler/assets/28784869/7ea5302a-ce4c-4ee8-8ff8-39ab14e8537e

### HyperCeiler 设备信息

Debug Info by HyperCeiler

VersionName = 2.4.146_a014a763_r3182
VersionCode = 146
BuildTime = (UTC+0:00) 2024-06-13 15:09:47
BuildType = canary
GitHash = a014a763a28f114703eb162811f95d4cc246259c
GitCode = 3182
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Xiaomi 13 Ultra
DeviceName = ishtar
Model = 2304FPN6DC
Brand = Xiaomi
Manufacture = Xiaomi
Board = kalama
Soc = SM8550
ModDevice = ishtar
Characteristics = nosdcard
Pad = false
FingerPrint = Xiaomi/ishtar/ishtar:14/UKQ1.230804.001/V816.0.9.0.UMACNXM:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = 085e839471398253

AndroidVersion = 34
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.9.0.UMACNXM
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = pangu-build-component-system-102368-sz8c7-jc30r-bn8fs
BuildDate = Mon Apr 29 07:58:40 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true

**Comment by mu7220** [comment]
第四点不是 bug：https://github.com/ReChronoRain/HyperCeiler/blob/MiuiX_V3_New/app%2Fsrc%2Fmain%2Fassets%2Ftips%2Ftips-zh_CN#L28-L28
