### ISSUE TITLE
系统框架-禁用持久性检查 无效

### ISSUE THREAD

**Issue by JerryZRF** [ReChronoRain/HyperCeiler#803]
### 须知

- [X] 我确认最新版依然存在此问题.
- [X] 我已排查已安装的所有模块的可能性，确认由本模块造成.
- [X] 我已经搜索过Issue Tracker，且并未查询到提交相同问题的 Issue.

### 问题描述

打开了 系统框架-禁用持久性检查 依旧无法安装持久性app

### 模块日志
```
[ 2024-08-11T18:08:22.949     1000:  1793:  2981 I/LSPosed-Bridge  ] [HyperCeiler][DisablePersistent:after][E]: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at P1.h.k(Unknown Source:457)
	at M1.i.afterHookedMethod(Unknown Source:22)
	at cW.ENoN.lUNm.LUExUCkjC.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.isPersistent(Unknown Source:8)
	at com.android.server.pm.parsing.PackageInfoUtils.appInfoFlags(PackageInfoUtils.java:904)
	at com.android.server.pm.parsing.pkg.PackageImpl.assignDerivedFields2(PackageImpl.java:2714)
	at com.android.server.pm.parsing.pkg.PackageImpl.<init>(PackageImpl.java:3381)
	at com.android.server.pm.parsing.PackageCacher.fromCacheEntryStatic(PackageCacher.java:87)
	at com.android.server.pm.parsing.PackageCacher.fromCacheEntry(PackageCacher.java:73)
	at com.android.server.pm.parsing.PackageCacher.getCachedResult(PackageCacher.java:176)
	at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:153)
	at com.android.server.pm.ParallelPackageParser.parsePackage(ParallelPackageParser.java:128)
	at com.android.server.pm.ParallelPackageParser.lambda$submit$0(ParallelPackageParser.java:107)
	at com.android.server.pm.ParallelPackageParser.$r8$lambda$vh1E89mUxrNtwBW2gELaXdFi9Q4(Unknown Source:0)
	at com.android.server.pm.ParallelPackageParser$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.android.internal.util.ConcurrentUtils$1$1.run(ConcurrentUtils.java:65)
[ 2024-08-11T18:08:23.294     1000:  1793:  2981 I/LSPosed-Bridge  ] [HyperCeiler][DisablePersistent:after][E]: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.Boolean.booleanValue()' on a null object reference
	at P1.h.k(Unknown Source:457)
	at M1.i.afterHookedMethod(Unknown Source:22)
	at cW.ENoN.lUNm.LUExUCkjC.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.isPersistent(Unknown Source:8)
	at com.android.server.pm.parsing.PackageInfoUtils.appInfoFlags(PackageInfoUtils.java:904)
	at com.android.server.pm.parsing.pkg.PackageImpl.assignDerivedFields2(PackageImpl.java:2714)
	at com.android.server.pm.parsing.pkg.PackageImpl.<init>(PackageImpl.java:3381)
	at com.android.server.pm.parsing.PackageCacher.fromCacheEntryStatic(PackageCacher.java:87)
	at com.android.server.pm.parsing.PackageCacher.fromCacheEntry(PackageCacher.java:73)
	at com.android.server.pm.parsing.PackageCacher.getCachedResult(PackageCacher.java:176)
	at com.android.server.pm.parsing.PackageParser2.parsePackage(PackageParser2.java:153)
	at com.android.server.pm.ParallelPackageParser.parsePackage(ParallelPackageParser.java:128)
	at com.android.server.pm.ParallelPackageParser.lambda$submit$0(ParallelPackageParser.java:107)
	at com.android.server.pm.ParallelPackageParser.$r8$lambda$vh1E89mUxrNtwBW2gELaXdFi9Q4(Unknown Source:0)
	at com.android.server.pm.ParallelPackageParser$$ExternalSyntheticLambda0.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at com.android.internal.util.ConcurrentUtils$1$1.run(ConcurrentUtils.java:65)
```
### 复现步骤

打开系统框架-禁用持久性检查

安装修改的com.android.settings失败

Failure [INSTALL_FAILED_INVALID_APK: Package com.android.settings are not updateable.]

### HyperCeiler 设备信息
```
Debug Info by HyperCeiler

VersionName = 2.4.148_20240629
VersionCode = 148
BuildTime = (UTC+0:00) 2024-06-29 14:36:57
BuildType = release
GitHash = 489191ce
GitCode = 3194
Debug = false
ApplicationId = com.sevtinge.hyperceiler

MarketName = Redmi Note 11T Pro
DeviceName = xaga
Model = 22041216C
Brand = Redmi
Manufacture = Xiaomi
Board = xaga
Soc = MT6895Z/TCZA
ModDevice = xaga
Characteristics = nosdcard
Pad = false
FingerPrint = Redmi/xaga/xaga:14/UP1A.231005.007/V816.0.3.0.ULOCNXM:user/release-keys
Locale = zh-CN
Language = zh_CN
AndroidId = d772d67013dfc9d2

AndroidVersion = 34
MiuiVersion = 0.0
HyperOsVersion = 1.0
SystemVersion = V816.0.3.0.ULOCNXM
InternationalBuild = false
Builder = builder
RomAuthor = 
BaseOs = 
Host = builder-system-38281-414527569204383744
BuildDate = Thu Jul 18 13:11:13 UTC 2024

Signature = 46:4C:5C:9D:A2:8C:AE:E6:B3:28:8D:AE:13:2C:A3:6D:52:A1:64:89:E0:95:CF:7B:52:AC:A7:11:F0:93:82:3C
SignCheckPass = true
ModuleActive = true
RootPermission = true
```

**Comment by hrsthrt74** [comment]
设置不是持久性app吧，安装持久app的错误提示应该是这样的
`Failure [INSTALL_FAILED_INVALID_APK: Package com.android.systemui is a persistent app. Persistent apps are not updateable.]`

**Comment by JerryZRF** [comment]
> 设置不是持久性app吧，安装持久app的错误提示应该是这样的
> `Failure [INSTALL_FAILED_INVALID_APK: Package com.android.systemui is a persistent app. Persistent apps are not updateable.]`

那怎么安装设置呢
包管理服务的选项已经全开了

**Comment by Sevtinge** [comment]
这不是持久性检查的问题
